name = "MC-Essentials"
author = "Chris Tomlin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5830011a8fbb3f39999f8f62c34e2fd14129b21cd6331a64a6e74a9131353857"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
